version: '3'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        dockerImageTag: ${DOCKER_IMAGE_TAG}
    image: node_app:${DOCKER_IMAGE_TAG}
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"
    environment:
      - DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}
    container_name: node_app
    restart: alway
